### ISSUE TITLE
where the image is?

### ISSUE THREAD

**Issue by elgarbe** [alansrobotlab/rospberrycore#1]
So, that's the question, where the image is to download

**Comment by djhnsn** [comment]
Plus one.

**Comment by alansrobotlab** [comment]
Apologies for the delay.  The original release is available under releases here:
https://github.com/alansrobotlab/rospberrycore/releases/tag/v0.5-alpha

That being said, I'm getting back into the project and am working on a ROS2 update with whatever the current version of Raspian is.  After I can either find or convert to ROS2 the packages that I'm using I'll post something.  Thanks!

Alan

**Comment by djhnsn** [comment]
Cool 😎.
